spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled:
      routes:
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/auth/**
